//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace saafcity_fyp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Complaints
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Complaints()
        {
            this.Complainnts = new HashSet<Complainnts>();
            this.Complaint_Log = new HashSet<Complaint_Log>();
            this.Employees = new HashSet<Employees>();
        }
    
        public int Complaint_ID { get; set; }
        public Nullable<System.DateTime> Complaint_Time { get; set; }
        public string Complaint_Loction { get; set; }
        public string Complaint_Status { get; set; }
        public byte[] Complaint_Image { get; set; }
        public byte[] Verifiction_Image { get; set; }
        public Nullable<int> Depart_ID { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complainnts> Complainnts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Complaint_Log> Complaint_Log { get; set; }
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
